package com.example.demo.service.material;

import com.example.demo.model.MaterialIndexingStatus;
import com.example.demo.model.MaterialMetadataSnapshot;
import com.example.demo.model.MaterialVersionState;
import java.time.Instant;
import java.util.List;

public record StoredMaterialRecord(
    String id,
    String title,
    String sourceType,
    String originalFileName,
    String mediaType,
    String content,
    String normalizedContent,
    String contentHash,
    String sourceKey,
    String extractor,
    Boolean ocrUsed,
    Integer pageCount,
    List<StoredMaterialChunk> chunks,
    MaterialIndexingStatus status,
    MaterialVersionState versionState,
    String statusReasonCode,
    String statusReasonMessage,
    Instant createdAt,
    Instant updatedAt,
    int indexingAttempts,
    Instant nextRetryAt,
    String supersededByMaterialId,
    String supersedeReason,
    int lineageVersion,
    MaterialMetadataSnapshot metadata
) {
    public StoredMaterialRecord {
        metadata = metadata == null ? MaterialMetadataSnapshot.empty() : metadata;
    }

    public StoredMaterialRecord(
        String id,
        String title,
        String sourceType,
        String originalFileName,
        String mediaType,
        String content,
        String normalizedContent,
        String contentHash,
        String sourceKey,
        String extractor,
        Boolean ocrUsed,
        Integer pageCount,
        List<StoredMaterialChunk> chunks,
        MaterialIndexingStatus status,
        MaterialVersionState versionState,
        String statusReasonCode,
        String statusReasonMessage,
        Instant createdAt,
        Instant updatedAt
    ) {
        this(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            sourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            0,
            status == MaterialIndexingStatus.PENDING ? updatedAt : null,
            null,
            null,
            0,
            MaterialMetadataSnapshot.empty()
        );
    }

    public StoredMaterialRecord(
        String id,
        String title,
        String sourceType,
        String originalFileName,
        String mediaType,
        String content,
        String normalizedContent,
        String contentHash,
        String sourceKey,
        String extractor,
        Boolean ocrUsed,
        Integer pageCount,
        List<StoredMaterialChunk> chunks,
        MaterialIndexingStatus status,
        MaterialVersionState versionState,
        String statusReasonCode,
        String statusReasonMessage,
        Instant createdAt,
        Instant updatedAt,
        MaterialMetadataSnapshot metadata
    ) {
        this(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            sourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            0,
            status == MaterialIndexingStatus.PENDING ? updatedAt : null,
            null,
            null,
            0,
            metadata
        );
    }

    public StoredMaterialRecord(
        String id,
        String title,
        String sourceType,
        String originalFileName,
        String mediaType,
        String content,
        String normalizedContent,
        String contentHash,
        String sourceKey,
        String extractor,
        Boolean ocrUsed,
        Integer pageCount,
        List<StoredMaterialChunk> chunks,
        MaterialIndexingStatus status,
        MaterialVersionState versionState,
        String statusReasonCode,
        String statusReasonMessage,
        Instant createdAt,
        Instant updatedAt,
        int indexingAttempts,
        Instant nextRetryAt,
        String supersededByMaterialId,
        String supersedeReason
    ) {
        this(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            sourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            indexingAttempts,
            nextRetryAt,
            supersededByMaterialId,
            supersedeReason,
            0,
            MaterialMetadataSnapshot.empty()
        );
    }

    public StoredMaterialRecord(
        String id,
        String title,
        String sourceType,
        String originalFileName,
        String mediaType,
        String content,
        String normalizedContent,
        String contentHash,
        String sourceKey,
        String extractor,
        Boolean ocrUsed,
        Integer pageCount,
        List<StoredMaterialChunk> chunks,
        MaterialIndexingStatus status,
        MaterialVersionState versionState,
        String statusReasonCode,
        String statusReasonMessage,
        Instant createdAt,
        Instant updatedAt,
        int indexingAttempts,
        Instant nextRetryAt,
        String supersededByMaterialId,
        String supersedeReason,
        MaterialMetadataSnapshot metadata
    ) {
        this(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            sourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            indexingAttempts,
            nextRetryAt,
            supersededByMaterialId,
            supersedeReason,
            0,
            metadata
        );
    }

    public StoredMaterialRecord withMetadata(MaterialMetadataSnapshot updatedMetadata) {
        return new StoredMaterialRecord(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            sourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            indexingAttempts,
            nextRetryAt,
            supersededByMaterialId,
            supersedeReason,
            lineageVersion,
            updatedMetadata
        );
    }

    public StoredMaterialRecord withLineageVersion(int updatedLineageVersion) {
        return new StoredMaterialRecord(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            sourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            indexingAttempts,
            nextRetryAt,
            supersededByMaterialId,
            supersedeReason,
            updatedLineageVersion,
            metadata
        );
    }

    public StoredMaterialRecord withSourceKey(String updatedSourceKey) {
        return new StoredMaterialRecord(
            id,
            title,
            sourceType,
            originalFileName,
            mediaType,
            content,
            normalizedContent,
            contentHash,
            updatedSourceKey,
            extractor,
            ocrUsed,
            pageCount,
            chunks,
            status,
            versionState,
            statusReasonCode,
            statusReasonMessage,
            createdAt,
            updatedAt,
            indexingAttempts,
            nextRetryAt,
            supersededByMaterialId,
            supersedeReason,
            lineageVersion,
            metadata
        );
    }
}
