package com.example.demo.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record HealthResponse(
    String application,
    String status,
    String timestamp,
    String directStatus,
    String ragStatus,
    String llmStatus,
    String llmReasonCode,
    String llmReasonMessage,
    String embeddingStatus,
    String embeddingReasonCode,
    String embeddingReasonMessage,
    String runtimeCachedAt,
    String ocrStatus,
    String ocrReasonCode,
    String ocrReasonMessage,
    List<String> ocrLanguages,
    String databaseStatus,
    String databaseReasonMessage,
    String vectorStatus,
    String vectorReasonMessage,
    String llmLastSuccessfulProbeAt,
    String embeddingLastSuccessfulProbeAt,
    String ragDegradedReasonCode,
    String ragDegradedReasonMessage,
    Integer indexingPendingCount,
    Integer indexingInProgressCount,
    Integer indexingFailedCount,
    String indexingNextRetryAt
) {
    public HealthResponse(
        String application,
        String status,
        String timestamp,
        String directStatus,
        String ragStatus,
        String llmStatus,
        String llmReasonCode,
        String llmReasonMessage,
        String embeddingStatus,
        String embeddingReasonCode,
        String embeddingReasonMessage,
        String runtimeCachedAt,
        String ocrStatus,
        String ocrReasonCode,
        String ocrReasonMessage,
        List<String> ocrLanguages,
        String databaseStatus,
        String databaseReasonMessage,
        String vectorStatus,
        String vectorReasonMessage
    ) {
        this(
            application,
            status,
            timestamp,
            directStatus,
            ragStatus,
            llmStatus,
            llmReasonCode,
            llmReasonMessage,
            embeddingStatus,
            embeddingReasonCode,
            embeddingReasonMessage,
            runtimeCachedAt,
            ocrStatus,
            ocrReasonCode,
            ocrReasonMessage,
            ocrLanguages,
            databaseStatus,
            databaseReasonMessage,
            vectorStatus,
            vectorReasonMessage,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }
}
