package com.example.demo.error;

public enum ErrorType {
    INVALID_REQUEST,
    NOT_FOUND,
    CONFLICT,
    PAYLOAD_TOO_LARGE,
    REQUEST_TIMEOUT,
    INTERNAL,
    STORAGE_FAILURE,
    PROVIDER_BAD_RESPONSE,
    PROVIDER_UNAVAILABLE,
    PROVIDER_TIMEOUT,
    INVALID_CONFIGURATION
}
